import React, { Fragment, memo, useState } from 'react'
import { Container } from 'react-bootstrap'
import BreadCrumbWidget from '../../components/BreadcrumbWidget'
import { Helmet } from "react-helmet";

const TermsofUse = memo(() => {
  const [title, setTitle] = useState("ARY ZAP - Terms & Conditions");
  return (
    <Fragment>
      <Helmet>
        <title>{`${title}`}</title>
      </Helmet>
        <BreadCrumbWidget title="Terms & Conditions"/>
        <div className="section-padding">
        <Container>
            <div className="title-box">
                <h4 className="mb-4">Terms & Conditions</h4>
                <p>1) Users only need to register on ARYZAP.com, then they can enjoy streaming</p>
                <p>2) Registered can avail all services of ARYZAP.com</p>
                <p>3) There is also an age limitations. ARYZAP.com services are not recommended to be used by children without involvement and approval of a parent or guardian.</p>
                <p>4) None of the ARY Zap trademarks(videos ,graphics, logos, scripts, and sounds) may be copied, downloaded.</p>
                <p>5) if you have any queries about these Terms, please contact us at: info@aryzap.com.</p>
                <p>This document is an electronic record in terms of information and rules that are applicable to the users. This electronic record is generated by a computer system and does not require any physical or digital signatures. This is a legal agreement between you, the user of the services of ARY ZAP’s website. If you do not agree to these terms and conditions, you are not entitled to use the services of this website.</p>
                <p>By visiting the site or using any of the services of ARY ZAP’s site you are agreeing to these terms and conditions. The content which is viewed on the ARY ZAP’s website is copyrighted material of ARY ZAP, and shall not be used by any other user without the permission of ARY ZAP’s website.</p>
                <p>You acknowledge and agree not to either directly or indirectly use ARY ZAP’s content from the website, whether it is in the form of video or text. The web-based service, or other means of content, should not be download, capture, reproduce, duplicate, archive, distribute, upload, publish, modify, translate, broadcast, perform, display, sell, transmit or retransmit the content or create any derivative work and/or material based on the content.</p>
                <p>You agree that your use of the website’s services and the content may give you the opportunity to view, share, post and comment in accordance with these terms and conditions. You agree that you will not misuse the content. In case if the site allows you to download or stream any of the contents therein, you agree that you will not use, sell, transfer or transmit the content to any person or upload the content on any other website, webpage or software.</p>
                <p className='mb-0'>You may have an opportunity to publish, transmit, submit, or otherwise post only comments. You agree that ARY ZAP shall have the right to unapproved any comment as needed. If you have any complaints relating to any material uploaded on the website, and then please contact: web@aryservices.com Your email must have your name, with the details of the objectionable post.</p>
            </div>
            <div className="title-box">
                <h4 className="mb-4">Privacy Policy</h4> 
                <p>This privacy policy covers the information about ARY ZAP; all the personal information of the users is collected if the users register with the website for any of the programs. The information is saved and only used for the registration purpose.</p>               
            </div>
        </Container>
        </div>
    </Fragment>
  )
})

export default TermsofUse